### ISSUE TITLE
Support variable number of arguments in macro

### ISSUE THREAD

**Issue by tindzk** [MetaStack-pl/MetaWeb#5]
Currently, the number of arguments is hard-coded. Figure out a way to allow a variable number. See [Macro.scala](https://github.com/MetaStack-pl/MetaWeb/blob/master/macros/src/main/scala/pl/metastack/metaweb/Macro.scala#L65).

**Comment by darkfrog26** [comment]
What you can do is create a Config class that takes in the arguments and that is passed to the Macro.
