### ISSUE TITLE
Better typing for HTML bindings

### ISSUE THREAD

**Issue by tindzk** [MetaStack-pl/MetaWeb#7]
MDN doesn't specify the actual attribute types. Therefore, we assume that all attributes are strings. However, we should better leverage Scala's type system as some attributes may only take numeric values. We should also map enumerations to ``case object``s.

**Comment by darkfrog26** [comment]
In most cases MDN does specify the attribute types. Specifically in the case of enums they list them. Parsing it though may prove rather difficult.

For example regarding enums see `formmethod`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

You can also see attribute types here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement
